version: '3.4'

# x-cache-from:
#   - &api-cache-from
#     cache_from:
#       - ${NGINX_IMAGE:-quay.io/googleapis/nginx}
#       - ${PHP_IMAGE:-quay.io/googleapis/php} 

services:
    php:
      build:
        context: ./api
        target: googleapis_php
        # <<: *api-cache-from
      image: ${PHP_IMAGE:-quay.io/googleapis/php}
      healthcheck:
        interval: 10s
        timeout: 3s
        retries: 3
        start_period: 30s
      volumes:
        - ./api:/srv/api:rw,cached
        - ./api/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
        # if you develop on Linux, you may use a bind-mounted host directory instead
        # - ./api/var:/srv/api/var:rw
  
    api:
      build:
        context: ./api
        target: googleapis_nginx
        # <<: *api-cache-from
      image: ${NGINX_IMAGE:-quay.io/googleapis/nginx}
      depends_on:
        - php
      volumes:
        - ./api/public:/srv/api/public:ro
      ports:
        - target: 80
          published: 8080
          protocol: tcp

    client:
      build:
        context: ./client
        target: googleapis_client_development
        cache_from:
          - ${CLIENT_IMAGE:-quay.io/googleapis/client}
      image: ${CLIENT_IMAGE:-quay.io/googleapis/client}
      environment:
        - API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT=http://api
        - API_PLATFORM_CLIENT_GENERATOR_OUTPUT=src
      volumes:
        - ./client:/usr/src/client:rw,cached
      links:
        - api
      ports:
        - target: 3000
          published: 80
          protocol: tcp